spring.application.name=reservas

# H2 Database (persistente en disco)
spring.datasource.url=jdbc:h2:file:./data/rustica
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 Console (opcional, para ver la BD en el navegador)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#Configuracion de springmail con una cuenta de google
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=federicotabib@gmail.com
spring.mail.password=ygun qlnd ywua ogaj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=1000MB

jwt.secret=01123581321345589144233377610987159725844181676510946177112865746368750251219174049317711286574636875025121917404931771128657463687502512
jwt.expiration=86400000